# Generated by Django 5.0.9 on 2024-09-10 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_weightrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightrecord",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
