# Generated by Django 5.0.9 on 2024-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_armmeasurement_beltmeasurement_calfmeasurement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightrecord",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
