# Generated by Django 5.0.9 on 2024-09-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_weightrecord_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightmeasurement",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
